# Matteuppgifter - repetition av Excel-jobbet, nu i Python
## Genomgång av matteuppgifterna i “Matematik från yrkeshögskolan”, kapitel 10
### *Michael Broström, michael@intertec.se, 0706683090*


In [ ]:
# Jag börjar med det viktigaste - importera paket och grunddata.
# Jag använder pandas och numpy som verktyg eftersom det underlättar hanteringen. 

import pandas as pd
import numpy as np

# Hämta in Excel-filen
file = "D:/Downloads/Övningsuppgifter YH Matematik.xlsx"


Ta in och formatera matriserna för uppgift 10.2.1

In [49]:
# Läs in alla data.

all_data = pd.read_excel(file, sheet_name='Blad1',
                         usecols='A:R', skiprows=3, nrows=2, header=None).values

# Extrahera matriser genom att dela upp kolumnerna
A = all_data[:, 0:3]    
B = all_data[:, 4:7]    
C = all_data[:, 8:10]    
D = all_data[:, 11:13]   
E = all_data[:, 14:15]  
I_matrix = all_data[:, 16:18]  

print("A =\n", A)
print("\nB =\n", B)
print("\nC =\n", C)
print("\nD =\n", D)
print("\nE =\n", E)
print("\nI =\n", I_matrix)


A =
 [[ 2.  1. -1.]
 [ 1. -1.  1.]]

B =
 [[ 4. -2.  1.]
 [ 2. -4. -2.]]

C =
 [[1. 2.]
 [2. 1.]]

D =
 [[3. 4.]
 [4. 3.]]

E =
 [[1.]
 [2.]]

I =
 [[1. 0.]
 [0. 1.]]


## Så tar vi itu med uppgifterna. 


10.2.1 a)

In [ ]:
# Metod 1: Skalär-multiplikation (vanligast)
result_a1 = 2 * A

# Metod 2: Addition A + A
result_a2 = A + A

# Visa resultat
print("a) 2A (multiplikation) =")
print(result_a1)

print("\na) 2A (addition) =")
print(result_a2)

# Verifiera att båda metoderna ger samma resultat
print("\nÄr metoderna lika?", np.array_equal(result_a1, result_a2))


Kör på med alla uppgifterna.

In [47]:
result_b = B - 2 * A

print("Uppgift a")
print (result_b)
print()

result_c = "Inte samma dimensoner"

print("Uppgift c")
print (result_c)
print()

result_d = 2 * D - 3 * C

print("Uppgift d")
print (result_d)
print()

result_e = D.T + 2 * D

print("Uppgift e")
print (result_e)
print()

result_e2 = np.transpose(D) + 2 * D

print("Uppgift e - med transpose från numpy istf bara D.T")
print (result_e2)
print()

result_f = 2 * C.T - 2 * D.T

print("Uppgift f")
print (result_f)
print()



# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# Cell In[40], line 37
#      34 print (result_f)
#      35 print()
# ---> 37 result_g = A.T - B
#      39 print("Uppgift g")
#      40 print (result_g)

# ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

# result_g = A.T - B


print("Uppgift g - går ej p.g.a. olika dimensioner")
# print (result_g)
print()

# result_h

print("Uppgift h går ej p.g.a. att antal kolumner i A(3) ej är samma som rader i C (2)")
# print (result_f)
print()



Uppgift a
[[ 0. -4.  3.]
 [ 0. -2. -4.]]

Uppgift c
Inte samma dimensoner

Uppgift d
[[3. 2.]
 [2. 3.]]

Uppgift e
[[ 9. 12.]
 [12.  9.]]

Uppgift e - med transpose från numpy istf bara D.T
[[ 9. 12.]
 [12.  9.]]

Uppgift f
[[-4. -4.]
 [-4. -4.]]

Uppgift g - går ej p.g.a. olika dimensioner

Uppgift h går ej p.g.a. att antal kolumner i A(3) ej är samma som rader i C (2)



In [55]:
result_i = C @ D

print("Uppgift i")
print (result_i)
print()

result_j = C @ B

print("Uppgift j")
print (result_j)
print()

result_k = C @ I_matrix

print("Uppgift k")
print (result_k)
if np.array_equal(result_k, C):
    print("Identitetsmatrisen påverkar inte ursprungsmatrisen vid en multiplicering")
print()

result_l = A @ B.T

print("Uppgift l")
print (result_l)
print()




Uppgift i
[[11. 10.]
 [10. 11.]]

Uppgift j
[[  8. -10.  -3.]
 [ 10.  -8.   0.]]

Uppgift k
[[1. 2.]
 [2. 1.]]
Identitetsmatrisen påverkar inte ursprungsmatrisen vid en multiplicering

Uppgift l
[[5. 2.]
 [7. 4.]]



Uppgift 10.2.2

In [57]:
A = np.array([
        [2,3,4], 
        [5,4,1]
        ])

AAT = A @ A.T

print(AAT)
print("En matris multiplicerad med sig själv transponerad blir alltid symmetrisk - d.v.s. förändras inte vid transponering")

[[29 26]
 [26 42]]
En matris multiplicerad med sig själv transponerad blir alltid symmetrisk - d.v.s. förändras inte vid transponering


Uppgift 10.2.3

In [62]:
# Verifiera att AB = AC, men att B != C (det senare ser vi visuellt)
A = np.array([
    [1,2],
    [2,4]    
])

B = np.array([
    [2,1],
    [1,3]
])

C = np.array([
    [4,3],
    [0,2]
])

AB = A @ B

AC = A @ C

print (AB)
print ()
print (AC)
print ()
if np.array_equal(AB, AC):
    print("Matriserna är identiska trots att B och C inte är det")
print()



[[ 4  7]
 [ 8 14]]

[[ 4  7]
 [ 8 14]]

Matriserna är identiska trots att B och C inte är det



Uppgift 10.2.4

In [69]:
# Skriv det linjära ekvationssystemet nedan på formen Ax = b
# 3x1 + 2x2 + 4x3 = 7
# 2x1 + 3x2 = 8x3 = 4
# 4x1 + 1x2 + 3x3 = 11
# 7x1 + 1x2 + 5x3 = 9

#Manuellt

A = np.array([
    [3,2,4],
    [2,3,8],
    [4,1,3],
    [7,1,5]
])

x = np.array([
    ["x1"],
    ["x2"],
    ["x3"]
])

b = np.array([
    [7],
    [4],
    [11],
    [9]
])

print(f"A\n{A} \n* \nx\n{x} \n= \nb\n{b}")

A
[[3 2 4]
 [2 3 8]
 [4 1 3]
 [7 1 5]] 
* 
x
[['x1']
 ['x2']
 ['x3']] 
= 
b
[[ 7]
 [ 4]
 [11]
 [ 9]]
